### ISSUE TITLE
A modification for newer versions of numpy

### ISSUE THREAD

**Issue by VincentJYZhang** [ThanatosShinji/onnx-tool#23]
I like this tool very much, and I use it often, but when I use `model_profile` on the onnx officially provided [Yolov4](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/yolov4), the following error occurs:
```
/usr/local/lib/python3.10/dist-packages/onnx_tool/tensor.py:100: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  if ndtype == numpy.str:
Traceback (most recent call last):
  File "/shareFolder/prj_py/common/model_utils/model_analysis.py", line 49, in <module>
    profile_dynamic_input_model(modelpath, inputs, save_csv_file='temp.csv')
  File "/shareFolder/prj_py/common/model_utils/model_analysis.py", line 21, in profile_dynamic_input_model
    onnx_tool.model_profile(model, input_dict, savenode=save_csv_file)
  File "/usr/local/lib/python3.10/dist-packages/onnx_tool/__init__.py", line 86, in model_profile
    g = Graph(m.graph, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/onnx_tool/graph.py", line 168, in __init__
    self.__init_graph_from_onnxproto__(g, noderename)
  File "/usr/local/lib/python3.10/dist-packages/onnx_tool/graph.py", line 243, in __init_graph_from_onnxproto__
    tensor = Tensor(initial)
  File "/usr/local/lib/python3.10/dist-packages/onnx_tool/tensor.py", line 361, in __init__
    self.numpy = tensorproto2ndarray(t)
  File "/usr/local/lib/python3.10/dist-packages/onnx_tool/tensor.py", line 100, in tensorproto2ndarray
    if ndtype == numpy.str:
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'str'.
```

My numpy version is 1.24.2. I read [the official description of Numpy](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) and found that the aliases of builtin type, `numpy.str`, is deprecated.

I checked the source code, and only need to modify the [line 105](https://github.com/ThanatosShinji/onnx-tool/blob/main/onnx_tool/tensor.py#L105) of `tensor.py` to solve this problem:

```
# raw line 105:
if ndtype == numpy.str:
# modified to:
if ndtype == numpy.str_:
```

New versions of Numpy are supported with this simple modification and my program also runs successfully. I hope the author can add this modification to the new version.

Hope this project will be better and better.

**Comment by ThanatosShinji** [comment]
Thanks for your report! Good work!

**Comment by ThanatosShinji** [comment]
The issue has been fixed with v0.6.3.

**Comment by ThanatosShinji** [comment]
v0.6.4 fixed other numpy data types and tested with numpy v1.24.2

**Comment by ThanatosShinji** [comment]
This issue will be closed as fixed if there is no more information.
