### ISSUE TITLE
dynamic bs input model error

### ISSUE THREAD

**Issue by rGitcy** [ThanatosShinji/onnx-tool#44]
I use tool to analyse onnx model meet the error:
Traceback (most recent call last):
  File "onnx_dynamic_analyse.py", line 92, in <module>
    onnx_tool.model_profile(model, input, savenode=save_path, hidden_ops=[])
  File "/usr/local/lib/python3.8/site-packages/onnx_tool/__init__.py", line 84, in model_profile
    g.shape_infer(dynamic_shapes)
  File "/usr/local/lib/python3.8/site-packages/onnx_tool/graph.py", line 828, in shape_infer
    oshapes = node.shape_infer(itensors)
  File "/usr/local/lib/python3.8/site-packages/onnx_tool/node.py", line 2056, in shape_infer
    assert raw == volume(newshape)
AssertionError

please help，thx!

**Comment by ThanatosShinji** [comment]
Hi, your problem is a model-related problem. In this case, either you need to share the model file with me, or you need to find out which op's shape inference result is wrong.
