### ISSUE TITLE
Error for input shape to operate sample code

### ISSUE THREAD

**Issue by ohjunee** [ThanatosShinji/onnx-tool#45]
**Describe the bug**
```python
import onnx_tool
modelpath = 'poc_internals/LGE_2023/Internal/models/onnx/resnet50-v1-12.onnx'
onnx_tool.model_profile(modelpath) # pass file name
``` 
in this code, i got an error.

```powershell
Traceback (most recent call last):
  File "/home/ojun.kwon/workspace/ojun.kwon/LGE_POC/poc_internals/LGE_2023/Internal/onnt_tool_test.py", line 3, in <module>
    onnx_tool.model_profile(modelpath) # pass file name
  File "/home/ojun.kwon/workspace/ojun.kwon/LGE_POC/InfOptim/lib/python3.10/site-packages/onnx_tool/__init__.py", line 84, in model_profile
    g.shape_infer(dynamic_shapes)
  File "/home/ojun.kwon/workspace/ojun.kwon/LGE_POC/InfOptim/lib/python3.10/site-packages/onnx_tool/graph.py", line 809, in shape_infer
    raise ValueError(
ValueError: The input tensor data's shape [N,3,224,224] is not valid, Please set it to a valid shape.
``` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by ohjunee** [comment]
oh i got it..

When the following inputs were inserted into the dynamic_shapes, 

```python
import onnx_tool
from onnx_tool import create_ndarray_f32
modelpath = 'poc_internals/LGE_2023/Internal/models/onnx/resnet50-v1-12.onnx'
onnx_tool.model_profile(modelpath, {'data': create_ndarray_f32((1, 3, 224, 224))}) # pass file name
``` 

the following results were obtained.

```powershell
...
resnetv17_stage4_activation2      Relu                100,352        0.00%       401,408      0.16%       0           0.00%       1x2048x7x7    1x2048x7x7
resnetv17_pool1_fwd               GlobalAveragePool   108,544        0.00%       8,192        0.00%       0           0.00%       1x2048x7x7    1x2048x1x1
flatten_473                       Flatten             0              0.00%       8,192        0.00%       0           0.00%       1x2048x1x1    1x2048
resnetv17_dense0_fwd              Gemm                2,049,000      0.05%       8,200,000    3.33%       2,049,000   7.99%       1x2048        1x1000
Total                             _                   4,209,590,760  100%        246,441,280  100%        25,629,032  100%        _             _
```
