### ISSUE TITLE
About an issue encountered in running the command line "python -m onnx_tool ......"

### ISSUE THREAD

**Issue by xwentian2020** [ThanatosShinji/onnx-tool#83]
**Describe the bug**
In running the command line "python -m onnx_tool -i 'resnet50-v1-12.onnx'  -o 'resnet50_shapes.onnx'", the info promoted there was something unexpected, listed as follows.

PS H:\AIModels> python -m onnx_tool -i 'resnet50-v1-12.onnx'  -o 'resnet50_shapes.onnx'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\onnx-tool\sd_env\Lib\site-packages\onnx_tool\__main__.py", line 93, in <module>
    onnx_tool.model_profile(args.in_, dynamic, save_profile=args.file, save_model=args.out)
  File "G:\onnx-tool\sd_env\Lib\site-packages\onnx_tool\__init__.py", line 84, in model_profile
    g.shape_infer(dynamic_shapes)
  File "G:\onnx-tool\sd_env\Lib\site-packages\onnx_tool\graph.py", line 974, in shape_infer
    raise ValueError(
ValueError: The input tensor data's shape [N,3,224,224] is not valid, Please set it to a valid shape.

Any suggestions for solving the above issue?

**Comment by xwentian2020** [comment]
```
PS H:\AIModels> pip list -v
Package    Version Location                              Installer
---------- ------- ------------------------------------- ---------
numpy      1.26.4  G:\onnx-tool\sd_env\Lib\site-packages pip      
onnx       1.16.1  G:\onnx-tool\sd_env\Lib\site-packages pip      
onnx-tool  0.9.0   G:\onnx-tool\sd_env\Lib\site-packages pip      
pip        24.0    G:\onnx-tool\sd_env\Lib\site-packages pip      
protobuf   5.27.1  G:\onnx-tool\sd_env\Lib\site-packages pip      
setuptools 65.5.0  G:\onnx-tool\sd_env\Lib\site-packages pip      
tabulate   0.9.0   G:\onnx-tool\sd_env\Lib\site-packages pip    
```

**Comment by ThanatosShinji** [comment]
> ValueError: The input tensor data's shape [N,3,224,224] is not valid, Please set it to a valid shape.

you should specify a fixed input shape for your model
